### PR TITLE
Feat: [OR-156] Menu Rebrand

### PR DESCRIPTION
**Pull request by vicky-comeau**
Issue: OR-156

## Summary

Added the hopper style for the Menu

### CODE REVIEW

**Review by fraincs — APPROVED** [review]

**Comment by fraincs** [comment]
UI Tests Pending — 57 changes must be accepted as baselines.

**Comment by alexasselin008** [comment]
image
The icons aren't the same color as the text, i feel like this is a bug

**Comment by fraincs** [comment]
image

The icon and text do not share the same color, but should. Since the icon fill is set to currentColor you should set the color on the li item.

**Comment by vicky-comeau** [comment]
> image
> 
> The icon and text do not share the same color, but should. Since the icon fill is set to currentColor you should set the color on the li item.

I'll fix this. I will set it on the icon since we have --hop-neutral-icon. I don't really like doing this either but it would be future proof if ever the icon is a different color.

**Review by fraincs — APPROVED** [review]

**Pull request merged**
