### PR TITLE
fixed an issue where the initial color in avatar was not right

### PR DESCRIPTION
**Pull request by fraincs**
Avatar text color was not right, this fixes the issue.

### CODE REVIEW

**Review by alexasselin008 — COMMENTED** [review]
There is an issue with the build, i fixed it for next time. Chromatic was not linked to the PR, but here are the tests that changed: https://www.chromatic.com/build?appId=651ae5d6e3fe178614aea15e&number=241

**Review by alexasselin008 — CHANGES_REQUESTED** [review]
There is an issue with the build, i fixed it for next time. Chromatic was not linked to the PR, but here are the tests that changed: https://www.chromatic.com/build?appId=651ae5d6e3fe178614aea15e&number=241

**Comment by fraincs** [comment]
> There is an issue with the build, i fixed it for next time. Chromatic was not linked to the PR, but here are the tests that changed: https://www.chromatic.com/build?appId=651ae5d6e3fe178614aea15e&number=241

I found it odd that Chromatic was ✅

**Comment by fraincs** [comment]
> There is an issue with the build, i fixed it for next time. Chromatic was not linked to the PR, but here are the tests that changed: https://www.chromatic.com/build?appId=651ae5d6e3fe178614aea15e&number=241

I validated the changes in Chromatic and approved them.

**Review by alexasselin008 — COMMENTED** [review]
Your missing a changeset file

**Review by alexasselin008 — APPROVED** [review]

**Pull request merged**
